proxy_set_header Accept-Encoding "";
sub_filter_once on;
sub_filter '</head>' '<script src="https://grist.openelis-global.org/oe-review-widget.js" data-instance="testing" data-label="OpenELIS Testing" data-src="https://grist.openelis-global.org/uat/testing.json"></script></head>';
